# Generated by Django 2.0.5 on 2018-11-17 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加日期'),
        ),
    ]
