# Generated by Django 2.0.5 on 2018-11-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20181117_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(blank=True, default=0, verbose_name='教师年龄'),
        ),
    ]
