# Generated by Django 2.1.3 on 2018-12-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20181203_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='type',
            field=models.CharField(default='org', max_length=10, verbose_name='类型'),
        ),
    ]
