# Generated by Django 2.1.3 on 2018-12-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_courseorg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(default='teacher', max_length=10, verbose_name='类型'),
        ),
    ]
