# Generated by Django 2.1.3 on 2018-11-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='课程标签'),
        ),
    ]
