# Generated by Django 2.1.3 on 2018-11-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='学习时长(分钟)'),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='', verbose_name='视频链接'),
        ),
    ]
