# Generated by Django 2.0.5 on 2018-11-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20181117_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='click_unms',
            new_name='click_nums',
        ),
    ]
