# Generated by Django 2.0.5 on 2018-11-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20181117_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'ordering': ['-add_time'], 'verbose_name': '课程评论', 'verbose_name_plural': '课程评论'},
        ),
    ]
