# Generated by Django 2.1.3 on 2018-12-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20181129_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='users',
            new_name='user',
        ),
    ]
