# Generated by Django 2.1.3 on 2018-11-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181111_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_img',
            field=models.ImageField(default='image/2018/11/322767.jpg', upload_to='image/%Y/%m'),
        ),
    ]
